spring:
  application:
    name: spring-security

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

  session:
    timeout: 30m
    data:
      redis:
        repository-type: indexed
        namespace: spring:session:spring-security


  sql:
    init:
      mode: never


app:
  security:
    super-admin-email: ${SUPER_ADMIN_EMAIL:kavinda@example.com}