spring:
  application:
    name: spring-security

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never